In [ ]:
# def

In [ ]:
#35
"""Напишите функцию draw_triangle(), которая выводит звёздный прямоугольный треугольник с катетами, равными 
10, в соответствии с образцом:
*
**
***
****
*****
******
*******
********
*********
**********   """

In [1]:
def draw_triangle():
    for i in range(1, 11):
        print('*' * i)

draw_triangle()

*
**
***
****
*****
******
*******
********
*********
**********

In [ ]:
#36
"""Юный инженер! Твой робот-исследователь только что вернулся из миссии по неизведанной территории. 
Он записал координаты всех точек своего маршрута. Тебе нужно рассчитать общее расстояние, которое преодолел робот!
На вход программе подается кортеж координат (x, y) точек маршрута - trajectory = ((0, 0), (3, 0), (3, 4), (0, 0))
Вычислить суммарную длину пути между всеми точками.
Ожидаемый результат: 12.0 """

In [6]:
def calculate_total_distance(points):
    x, y = points[0][0], points[0][1]
    res = 0

    for p in points:
        res += ((x - p[0])**2 + (y - p[1])**2)**0.5
        x, y = p[0], p[1]

    return res


# Тест
trajectory = ((0, 0), (3, 0), (3, 4), (0, 0))
print(calculate_total_distance(trajectory))

12.0

In [ ]:
#37
"""Напишите функцию draw_triangle(fill, base), которая принимает два параметра:
fill – символ заполнитель;
base – величина основания равнобедренного треугольника;
а затем выводит его.
Гарантируется, что основание треугольника – нечётное число.
Input 1:
?
7
Output 1:
?
??
???
????
???
??
?                            """

In [10]:
def draw_triangle(fill, base):
    for i in range(1, base // 2 + 2):
        print(fill * i)
    
    for i in range(base // 2, 0, -1):
        print(fill * i)

draw_triangle(input(), int(input()))

?
??
???
????
???
??
?

In [ ]:
#38
"""Напишите функцию get_days(month), которая принимает в качестве аргумента номер месяца и возвращает количество дней в данном месяце.
Гарантируется, что передаваемый аргумент находится в диапазоне от 1 до 12 (включительно).
Считайте, что год является невисокосным. """

In [ ]:
def get_days(month):
    big = [1, 3, 5, 7, 8, 10, 12]
    small = [4, 6, 9, 11]
    if month in big:
        return 31
    elif month in small:
        return 30
    else:
        return 28

In [ ]:
#39
"""Напишите функцию get_factors(num), принимающую в качестве аргумента натуральное число и возвращающую список всех делителей данного числа.
Input 1:	
5
Output 1:                 
[1, 5]

Input 2:                
10
Output 2:                  
[1, 2, 5, 10]

Input 3:                 
36
Output 3:           
[1, 2, 3, 4, 6, 9, 12, 18, 36]        """

In [ ]:
# Напишите Ваш код здесь

In [ ]:
#40
"""Напомним, что строковый метод find('a') возвращает местоположение первого вхождения символа a в строке. 
Проблема заключается в том, что данный метод не находит местоположение всех символов а.
Напишите функцию с именем find_all(target, symbol), которая принимает два аргумента: строку target и символ symbol и возвращает список, 
содержащий все местоположения этого символа в строке.
Если указанный символ не встречается в строке, то следует вернуть пустой список.
Input 1:
abcdabcaaa
a
Output 1:
[0, 4, 7, 8, 9]

Input 2:
abcadbcaaa
e
Output 2:
[]           """

In [ ]:
# Напишите Ваш код здесь

In [ ]:
#41
"""Напишите функцию merge(list1, list2), которая принимает в качестве аргументов два отсортированных по возрастанию списка, 
состоящих из целых чисел, и объединяет их в один отсортированный список.
Можно использовать списочный метод sort(), а можно обойтись и без него. 
Input 1:
1 2 3
5 6 7 8
Output 1:
[1, 2, 3, 5, 6, 7, 8]

Input 2:
1 7 10 16
5 6 13 20
Output 2:
[1, 5, 6, 7, 10, 13, 16, 20]

Input 3:
1
2
Output 3:
[1, 2]     """

In [ ]:
# Напишите Ваш код здесь

In [ ]:
#42
"""Напишите функцию is_prime(num), которая принимает в качестве аргумента натуральное число и возвращает значение True, 
если число является простым, или False в противном случае.
Input 1:
1
Output 1:
False

Input 2:
10
Output 2:
False           """

In [ ]:
# Напишите Ваш код здесь

In [ ]:
#43
"""Напишите функцию f(x), которая возвращает значение следующей функции, определённой на всей числовой прямой:
Если x ≤ -2: f(x) = 1 - (x + 2)^2
Если -2 < x ≤ 2: f(x) = -x/2
Если x > 2: f(x) = (x - 2)^2 + 1
Input 1:
4.5
Output 1:
7.25

Input 2:
-4.5
Output 2:
-5.25
Input 3:
1
Output 3:
-0.5       """

In [ ]:
# Напишите Ваш код здесь

In [ ]:
#44
"""Напишите функцию modify_list(l), которая принимает на вход список целых чисел, удаляет из него все нечётные значения, 
а чётные нацело делит на два"""

In [ ]:
# Напишите Ваш код здесь

In [ ]:
#45
"""Напишите функцию is_password_good(password), которая принимает в качестве аргумента строковое значение пароля password и возвращает значение
True, если пароль является надёжным, или False в противном случае.
Пароль является надёжным, если:
его длина не менее 8 символов; 
он содержит как минимум одну заглавную букву (верхний регистр); 
он содержит как минимум одну строчную букву (нижний регистр);
он содержит хотя бы одну цифру. 
Input 1:
aaAA12qqp
Output 1:
True

Input 2:
aa13AN
Output 2:
False        """

In [ ]:
# Напишите Ваш код здесь

In [ ]:
#46
"""Напишите функцию is_palindrome(text), которая принимает в качестве аргумента строку text и возвращает значение True, если указанный текст 
является палиндромом, или False в противном случае.
Палиндром – это строка, которая читается одинаково в обоих направлениях
При проверке считайте большие и маленькие буквы одинаковыми, а также игнорируйте пробелы и символы ,.!?-.
Input 1:
Standart - smallest, sell Amstrad nats.
Output 1:
True

Input 2:
sjdflksjflksdjflsdjk sdlfhsdjfE#R#$$#R !!!!! sdjfnsdjkfnsd kjcvadsk
Sample Output 2:
False                                                                    """

In [ ]:
# Напишите Ваш код здесь

In [ ]:
#47
"""Напишите функцию is_correct_bracket(text), которая принимает в качестве аргумента непустую строку text, состоящую из символов ( и ) и 
возвращает значение True, если поступившая на вход строка является правильной скобочной последовательностью, или False в противном случае.
Правильной скобочной последовательностью называется строка, состоящая только из символов ( и ), где каждой открывающей скобке найдётся 
парная закрывающая скобка (при этом каждая открывающая скобка должна быть левее соответствующей ей закрывающей скобки).
Input 1:
())((((())))
Sample Output 1:
False

Input 2:
(()())
 Output 2:
True             """

In [ ]:
# Напишите Ваш код здесь

In [ ]:
#48
"""Напишите функцию convert_to_python_case(text), которая принимает в качестве аргумента строку в «верблюжьем регистре»
и преобразует его в «змеиный регистр».
Input 1:
ThisIsCamelCased
Output 1:
this_is_camel_cased

Input 2:
IsPrimeNumber
Output 2:
is_prime_number           """

In [ ]:
# Напишите Ваш код здесь

In [ ]:
#49
"""Напишите функцию solve(a, b, c), которая принимает в качестве аргументов три целых числа a, b, c – коэффициенты квадратного уравнения 
ax^2 + bx + c = 0 и возвращает его корни в порядке возрастания.
Гарантируется, что квадратное уравнение имеет хотя бы один корень.
Input 1:
1
-4
-5
Output 1:
-1.0 5.0

Input 2:
-2
7
-5
Output 2:
1.0 2.5          """

In [ ]:
# Напишите Ваш код здесь

In [ ]:
#50
"""Напишите функцию draw_triangle(), которая выводит звёздный равнобедренный треугольник с основанием и высотой, равными 
15 и 8 соответственно:
       *
      ***
     *****
    *******
   *********
  ***********
 *************
***************                  
Для вывода треугольника используйте цикл for.
Справа от звёздочек пробелов нет."""

In [ ]:
# Напишите Ваш код здесь

In [ ]:
#51
"""Напишите функцию compute_binom(n, k), которая принимает в качестве аргументов два натуральных числа n и k и 
возвращает значение биномиального коэффициента, который вычисляется по формуле: n!/(k!(n-k)!)
Реализуйте вспомогательную функцию factorial(n), вычисляющую факториал числа, или воспользуйтесь уже готовой функцией из модуля math. 
Обратите внимание, что функция compute_binom(n, k) должна возвращать целое число. 
Input 1:
1
1
Output 1:
1

Input 2:
2
1
Output 2:
2         """

In [ ]:
# Напишите Ваш код здесь

In [ ]:
#52
""Напишите функцию number_to_words(num), которая принимает в качестве аргумента натуральное число num и возвращает 
его словесное описание на русском языке. 1 <= num <= 99

In [ ]:
# Напишите Ваш код здесь

In [ ]:
#53
"""Напишите функцию get_month(language, number), которая принимает на вход два аргумента language – язык ru или en и number – номер месяца (от 
1 до 12 включительно) и возвращает название месяца на русском или английском языке.
Input 1:
ru
1
Output 1:
январь

Input 2:
en
2
Output 2:
february            """

In [ ]:
# Напишите Ваш код здесь

In [ ]:
#54
"""Магическая дата – это дата, когда день, умноженный на месяц, равен числу, образованному последними двумя цифрами года.
Напишите функцию is_magic(date), которая принимает в качестве аргумента строковое представление корректной даты и возвращает значение
True, если дата является магической, или False в противном случае.
Input 1:
10.06.1960
Output 1:
True

Input 2:
15.03.1945
Output 2:
True           """

In [ ]:
# Напишите Ваш код здесь

In [ ]:
#55
"""Панграмма – это фраза, содержащая в себе все буквы алфавита. Обычно панграммы используют для презентации шрифтов, чтобы можно было в одной фразе
рассмотреть все глифы. Напишите функцию is_pangram(text), которая принимает в качестве аргумента строку текста на английском языке и возвращает 
значение True, если текст является панграммой, или False в противном случае.
Гарантируется, что введённая строка содержит только буквы английского алфавита и пробелы.
Input 1:
Jackdaws love my big sphinx of quartz
Output 1:
True

Input 2:
razy Fredrick bought many very exquisite opal
Output 2:
False                   """

In [ ]:
# Напишите Ваш код здесь

In [ ]:
#56
"""Напишите программу, которая выводит максимальный элемент в  области квадратной матрицы (область звездочек).
*----
**---
***--
****-
*****

На вход программе подается натуральное число n – количество строк и столбцов в матрице, затем элементы матрицы (целые числа) построчно через пробел.
Программа должна вывести одно число – максимальный элемент в заштрихованной области квадратной матрицы.
Примечание. Элементы главной диагонали также учитываются"""
"""
Input 1:
3
1 4 5
6 7 8
1 1 6
Output 1:
7

Input 2:
4
0 1 4 6
0 0 2 5
0 0 0 7
0 0 0 0
Output 2:
0

Input 3:
2
6 0
7 9
Output 3:
9

Input 4:
3
-50 -10 -20
-19 -78 -70
-11 -12 -19
Output 4:
-11

In [ ]:
# Напишите Ваш код здесь

In [ ]:
#57
"""Научный робот провел серию измерений тремя разными датчиками! Вам нужно проанализировать собранные данные и найти для каждого датчика:
-Минимальное значение
-Максимальное значение
-Среднее арифметическое
Кортеж с показаниями - ((25, 30, 35), (30, 35, 40), (22, 28, 32), (27, 32, 37))

Подсказка: первый датчик - температура, второй - влажность, третий - давление
Данные 25, 30, 22, 27 - это данный первого датчика с разных измерений.
Ожидаемый результат: ((22, 30, 26.0), (28, 35, 31.2), (32, 40, 36.0))"""

In [ ]:
# Напишите Ваш код здесь

In [ ]:
#58
""" Квадратная матрица разбивается на четыре четверти, ограниченные главной и побочной диагоналями: верхнюю, нижнюю, левую и правую.
*       *
  *   *  
    *    
  *   *  
*       *
Напишите программу, которая вычисляет сумму элементов: верхней четверти; правой четверти; нижней четверти; левой четверти.

На вход программе подается натуральное число n – количество строк и столбцов в матрице, затем элементы матрицы (целые числа) построчно через пробел.
Программа должна вывести текст в соответствии с условием задачи.
Примечание. Элементы диагоналей не учитываются."""
"""
Input 1:
4
1 2 3 4
5 6 7 8
3 4 5 6
1 2 3 4
Output 1:
Верхняя четверть: 5
Правая четверть: 14
Нижняя четверть: 5
Левая четверть: 8

Input 2:
5
1 4 3 4 7
5 6 7 8 4
3 8 5 6 1
1 2 9 4 8
5 6 1 5 8
Output 2:
Верхняя четверть: 18
Правая четверть: 19
Нижняя четверть: 21
Левая четверть: 17

Input 3:
2
99 72
65 11
Output 3:
Верхняя четверть: 0
Правая четверть: 0
Нижняя четверть: 0
Левая четверть: 0     """

In [ ]:
# Напишите Ваш код здесь